namespace Threadlight.Mirroring.Editor {
using Threadlight.EditorUI;
using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;
public sealed partial class LiveMirroringSetupWindow {
    private const string SectionStateSurfaceId = "live-mirroring.sections";
    private LiveMirroringSetupCard CreateWorkspaceSection(
        string title,
        string description,
        ThreadlightEditorTone tone,
        string kind = "SECTION") {
        Object owner = currentSystem != null ? currentSystem : candidateRoot;
        string identity = $"{kind}:{title}";
        bool expanded = ThreadlightEditorPreferences.GetSessionState(
            SectionStateSurfaceId, owner, identity, true);
        return LiveMirroringSetupElements.CreateSection(
            title, description, tone, kind, expanded,
            value => ThreadlightEditorPreferences.SetSessionState(
                SectionStateSurfaceId, owner, identity, value));
    }
    private ThreadlightSerializedForm CreateSerializedForm(VisualElement parent,
        Color? interactionAccent = null) {
        Color accent = interactionAccent ?? ResolveInteractionAccent(parent);
        return
        new ThreadlightSerializedForm(
            serializedSystem,
            ApplySerializedChange,
            GetBoolean,
            GetTooltip,
            (element, title, body) => AddTooltip(element, title, body),
            () => accent);
    }
    private static Color ResolveInteractionAccent(VisualElement parent) {
        for (VisualElement current = parent; current != null; current = current.parent)
            if (current is LiveMirroringSetupCard card)
                return card.InteractionAccent;
        return ThreadlightEditorTheme.WorkspacePrefabAccent;
    }
    private void RenderFields(
        VisualElement parent,
        params ThreadlightFormField[] fields) =>
        CreateSerializedForm(parent).AddFields(ResolveContentHost(parent), fields);
    private T RenderField<T>(
        VisualElement parent,
        ThreadlightFormField field)
        where T : VisualElement =>
        CreateSerializedForm(parent).AddField(ResolveContentHost(parent), field) as T;
    private T RenderField<T>(
        VisualElement parent,
        ThreadlightFormField field,
        Color interactionAccent)
        where T : VisualElement =>
        CreateSerializedForm(parent, interactionAccent).AddField(
            ResolveContentHost(parent), field) as T;
    private static VisualElement ResolveContentHost(VisualElement parent) =>
        parent is ThreadlightDisclosureCard card ? card.Content : parent;
    private T AddTooltip<T>(T element, string title, string body)
        where T : VisualElement {
        return tooltipLayer != null
            ? tooltipLayer.Register(element, title, body)
            : element;
    }
    private bool IsCurrentSystemManagedExternally(out string managerName) {
        managerName = null;
        return currentSystem != null &&
            LiveMirroringSetupUtility.TryGetManagingTool(
                LiveMirroringSetupUtility
                    .ResolveAuthoringRoot(currentSystem)?.gameObject,
                currentSystem,
                out managerName);
    }
    private static string GetTooltip(string path) {
        if (path == "constraintTargetsObjectName") return "Names the generated folder that contains source and mirrored targets.";
        if (path == "targetNamePrefix") return "Adds this prefix to every generated target name.";
        if (path == "sourceSideLabel") return "Labels generated targets on the configured source side.";
        if (path == "mirroredSideLabel") return "Labels generated targets on the opposite side.";
        if (path == "sourceFolderName") return "Names the folder containing source-side targets.";
        if (path == "mirroredFolderName") return "Names the folder containing generated opposite-side targets.";
        if (path == "removeUnusedGeneratedTargets") return "Removes only pristine Threadlight-owned targets that are no longer configured; edited or creator-owned objects are preserved.";
        if (path == "addVrcfuryArmatureLinks") return "Adds or updates VRCFury Armature Link components on targets generated by this tool when VRCFury is installed.";
        if (path == "liveMirror") return "Continuously mirror enabled pairs while editing.";
        if (path == "mirrorCenter") return "The transform whose position and orientation define the mirror plane.";
        if (path == "mirrorOptions.mirrorAxis") return "Choose which local axis of the mirror center separates the two sides.";
        if (path == "mirrorOptions.mirrorPosition") return "Mirror the source position onto the opposite side.";
        if (path == "mirrorOptions.mirrorRotation") return "Mirror the source rotation onto the opposite side.";
        if (path == "mirrorOptions.mirrorScale") return "Copy the source scale to the mirrored target.";
        if (path == "applyScaleReference") return "Required for Constraint Targets. Keep the prefab scale reference and every target at one shared world scale.";
        if (path == "scaleReference") return "Assign the prefab object or content container that should scale. It must be separate from the prefab root and target hierarchy.";
        if (path == "addParentConstraintToPrefabContainer") return "Adds a VRC Parent Constraint to the prefab scale reference and assigns every generated source and mirrored grip as a constraint source.";
        if (path == "targetLocalPosition") return "Sets the local position assigned to newly generated targets.";
        if (path == "targetLocalEulerRotation") return "Sets the local Euler rotation assigned to newly generated targets.";
        if (path == "targetLocalScale") return "Sets the local scale assigned to newly generated targets.";
        if (path == "applyDefaultTransformToExistingTargets") return "Allows rebuilding to update transforms on existing Threadlight-owned targets.";
        if (path.StartsWith("scaleHandles.Array.data[")) return "An additional object that can drive or receive the setup's shared scale.";
        if (path.EndsWith(".createOppositeTarget")) return "Creates and retains an opposite-side target for this entry.";
        if (path.EndsWith(".useGlobalSideLabels")) return "Uses the R/L labels configured in Target Organization.";
        if (path.EndsWith(".sourceSideLabel")) return "Overrides the source-side label for this target.";
        if (path.EndsWith(".mirroredSideLabel")) return "Overrides the opposite-side label for this target.";
        if (path.EndsWith(".pairName")) return "A readable label for identifying this pair in the setup window.";
        if (path.EndsWith(".sourceTarget")) return "The object whose transform drives this pair. A target is generated when this is left empty.";
        if (path.EndsWith(".sourceBone")) return "Chooses the avatar bone followed by the source target's VRCFury Armature Link.";
        if (path.EndsWith(".mirroredTarget")) return "The object updated on the opposite side. A target is generated when this is left empty.";
        if (path.EndsWith(".mirroredBone")) return "Chooses the avatar bone followed by the mirrored target's VRCFury Armature Link.";
        if (path.EndsWith(".mirroredRotationOffset")) return "An extra local rotation applied after mirroring the source.";
        if (path == "showScenePreview") return "Show non-interactive ghost copies at the configured mirror targets.";
        if (path == "previewSource") return "The object copied to create the scene preview ghosts.";
        if (path == "previewMaterial") return "The material used by preview ghosts. The included Ghost Material is used when this is empty, with Unity's default material as a fallback.";
        if (path == "generateThreadlightComponentsBootstrapper") return "Create the guarded temporary installer that can accompany an exported Unity package when ThreadLight Components is not installed through VCC.";
        if (path == "threadlightComponentsBootstrapperFolderPath") return "Choose the Assets folder used for the temporary installer. The installer removes its owned files after completing installation.";
        return string.Empty;
    }
    private static Label CreateNativeLikeSectionLabel(string text, Color? accent = null) =>
        ThreadlightEditorElements.CreateSubcategoryLabel(text, accent ??
            ThreadlightEditorTheme.Palette(ThreadlightEditorTone.Feature).Accent);
    private bool GetBoolean(string path) {
        if (!PrepareSerializedSystem())
            return false;
        SerializedProperty property = serializedSystem.FindProperty(path);
        return property != null && property.boolValue;
    }
}
}
